title: " os incrível 
genre: "",  = ação 
ageRating: ,  = livre
synopsis: "", =Depois do governo banir o uso de superpoderes, o maior herói do planeta, o Sr. Incrível, vive de forma pacata com sua família. Apesar de estar feliz com a vida doméstica, o Sr. Incrível ainda sente falta dos tempos em que viveu como super-herói, e sua grande chance de entrar em ação novamente surge quando um velho inimigo volta a atacar. Só que agora ele precisa contar com a ajuda de toda a família para vencer o vilão.
trailer: "" = Os Incríveis - Trailer - Dublado

title: "power rangers "
genre: "",  = Ação 
ageRating: ,  = 10
synopsis: "", = A jornada de cinco adolescentes que devem buscar algo extraordinário quando eles tomam consciência que a sua pequena cidade Angel Grove - e o mundo - estão à beira de sofrer um ataque alienígena. Escolhidos pelo destino, eles irão descobrir que são os únicos que poderão salvar o planeta. Mas para isso, eles devem superar seus problemas pessoais e juntarem sua forças, antes que seja tarde demais.
trailer: "" = https://youtu.be/5kIe6UZHSXw?si=BjTgZCWMIMl4HiFm


title: " ",Vingadores: guerra infinita
genre: "",  = ação 
ageRating: , = 12
synopsis: "", =Em Vingadores: Guerra Infinita, Thanos (Josh Brolin) enfim chega à Terra, disposto a reunir as Joias do Infinito. Para enfrentá-lo, os Vingadores precisam unir forças com os Guardiões da Galáxia, ao mesmo tempo em que lidam com desavenças entre alguns de seus integrantes.
trailer: "" = Vingadores - Guerra Infinita |  Trailer Oficial Legendado

title: " ",Esquema de risco
genre: "",  = ação 
ageRating: ,  = 14
synopsis: "", =O espião Fortune deve impedir a venda de uma tecnologia mortal administrada por um grande negociador de armas. Para isso, ele se junta a um time de elite, incluindo a maior estrela de Hollywood.
trailer: "" = Esquema De Risco: Operação Fortune | Trailer Dublado

title: " ", Logan
genre: "",  = ação 
ageRating: ,  = 16
synopsis: "", =Em 2029, Logan (Hugh Jackman) ganha a vida como chofer de limousine para cuidar do nonagenário Charles Xavier (Patrick Stewart). Debilitado fisicamente e esgotado emocionalmente, ele é procurado por Gabriela (Elizabeth Rodriguez), uma mexicana que precisa da ajuda do ex-X-Men para defender a pequena Laura Kinney / X-23 (Dafne Keen). Ao mesmo tempo em que se recusa a voltar à ativa, Logan é perseguido pelo mercenário Donald Pierce (Boyd Holbrook), interessado na menina.
trailer: "" = Logan | Official Trailer [HD] | 20th Century FOX


title: " ",Toy story
genre: "",  = comedia 
ageRating: ,  = livre
synopsis: "", =O aniversário de Andy está chegando e os brinquedos estão nervosos. Afinal de contas, eles temem que um novo brinquedo possa substituí-los. Liderados por Woody, um caubói que é também o brinquedo predileto de Andy, eles montam uma escuta que lhes permite saber dos presentes ganhos. Entre eles está Buzz Lightyear, o boneco de um patrulheiro espacial, que logo passa a receber mais atenção do garoto. Isto aos poucos gera ciúmes em Woody, que tenta fazer com que ele caia atrás da cama. Só que o plano dá errado e Buzz cai pela janela. É o início da aventura de Woody, que precisa resgatar Buzz também para limpar sua barra com os outros brinquedos.
trailer: "" = Toy Story | Original Trailer | Disney+


title: " cronicas de natal"
genre: "",  = comédia 
ageRating: ,  = 10
synopsis: "", =Os irmãos Kate e Teddy causam um acidente com o trenó do Papai Noel e embarcam em uma noite alucinante para tentar salvar o Natal.
trailer: "" = https://youtu.be/a2ze1SV3an0?si=cLytmSl8oxbcYKQD


title: " ",O auto da compadecida 
genre: "",  = Comédia 
ageRating: ,  = 12
synopsis: "", =As aventuras dos nordestinos João Grilo (Matheus Natchergaele), um sertanejo pobre e mentiroso, e Chicó (Selton Mello), o mais covarde dos homens. Ambos lutam pelo pão de cada dia e atravessam por vários episódios enganando a todos do pequeno vilarejo de Taperoá, no sertão da Paraíba. A salvação da dupla acontece com a aparição da Nossa Senhora (Fernanda Montenegro). Adaptação da obra de Ariano Suassuna.
trailer: "" = O AUTO DA COMPADECIDA 2000 Trailer


title: " ", Um espião e meio 
genre: "",  = Comédia 
ageRating: ,  = 14
synopsis: "", =Antes de se tornar um agente da CIA, Bob sofria bullying na época do colégio. Na agência, ele precisa resolver um caso ultrassecreto e recorre a um antigo colega, popular nos tempos da escola, hoje contador.
trailer: "" = Um Espião e Meio - Trailer Oficial


title: " ",deadpool
genre: "",  = comédia 
ageRating: ,  = 16
synopsis: "", =Ex-militar e mercenário, Wade Wilson (Ryan Reynolds) é diagnosticado com câncer em estado terminal, porém encontra uma possibilidade de cura em uma sinistra experiência científica. Recuperado, com poderes e um incomum senso de humor, ele torna-se Deadpool e busca vingança contra o homem que destruiu sua vida.
trailer: "" = Deadpool | Teaser Trailer Oficial | Legendado HD

title: " a vida é bela"
genre: "",  = drama 
ageRating: ,  = livre
synopsis: "", =Durante a Segunda Guerra Mundial na Itália, o judeu Guido e seu filho Giosué são levados para um campo de concentração nazista. Afastado da mulher, ele precisa usar sua imaginação para fazer o menino acreditar que estão participando de uma grande brincadeira, com o intuito de protegê-lo do terror e da violência ao redor.
trailer: "" =https://youtu.be/8CTjcVr9Iao?si=llfSVfbAiXtVTUJo


title: " ", Extraordinario
genre: "",  = drama
ageRating: ,  = 10
Synopsis: "", =  Auggie Pullman é um garoto que nasceu com uma deformidade facial e precisou passar por 27 cirurgias plásticas. Aos 10 anos, ele finalmente começa a frequentar uma escola regular, como qualquer outra criança, pela primeira vez. No quinto ano, ele precisa se esforçar para conseguir se encaixar em sua nova realidade.
trailer: "" = Extraordinário | Trailer Oficial Legendado

title: " central do Brasil 
genre: "",  = drama
ageRating: = 12
synopsis: "" = Dora, uma amargurada ex-professora, ganha a vida escrevendo cartas para pessoas analfabetas, que ditam o que querem contar às suas famílias. Ela embolsa o dinheiro sem sequer postar as cartas. Um dia, Josué, o filho de nove anos de idade de uma de suas clientes, acaba sozinho quando a mãe é morta em um acidente de ônibus. Ela reluta em cuidar do menino, mas se junta a ele em uma viagem pelo interior do Nordeste em busca do pai de Josué, que ele nunca conheceu.
trailer: "" =Central do Brasil | Festival do Rio 2018

title: " ",A espera de um milagre
genre: "",  = drama
ageRating: ,  = 14
synopsis: "", =Um carcereiro tem um relacionamento incomum e comovente com um preso que está no corredor na morte: Coffey, um negro enorme, condenado por ter matado brutalmente duas gêmeas de nove anos. Ele tem tamanho e força para matar qualquer um, mas seu comportamento é completamente oposto à sua aparência. Além de ser simples, ingênuo e ter pavor do escuro, ele possui um dom sobrenatural. Com o passar do tempo, o carcereiro aprende que, às vezes, os milagres acontecem nos lugares mais inesperados.
trailer: "" = À Espera de Um Milagre - Trailer Legendado 1999

title: " ",A baleia
genre: "",  = drama
ageRating: ,  = 16
synopsis: "", = Homem obeso e solitário busca se reconectar com filha adolescente em uma última chance de redenção.
trailer: "" =A BALEIA Trailer Brasileiro Dublado (2023)


title: " ",shrek
genre: "",  = animação 
ageRating: ,  = livre
synopsis: "", =Um ogro tem sua vida invadida por personagens de contos de fadas que acabam com a tranquilidade de seu lar. Ele faz um acordo pra resgatar uma princesa.
trailer: "" = Shrek (2001) Trailer #1 | Movieclips Classic Trailers

title: " ",coranile
genre: "",  = animação 
ageRating: ,  = 10
synopsis: "", =Enquanto explora sua nova casa à noite, a pequena Coraline descobre uma porta secreta que contém um mundo parecido com o dela, porém melhor em muitas maneiras. Todos têm botões no lugar dos olhos, os pais são carinhosos e os sonhos de Coraline viram realidade por lá. Ela se encanta com essa descoberta, mas logo percebe que segredos estranhos estão em ação: uma outra mãe e o resto de sua família tentam mantê-la eternamente nesse mundo paralelo.
trailer: "" =Coraline e o Mundo Secreto｜Trailer oficial dublado｜2009

title: " kimi no na wa"
genre: "",  = animação 
ageRating: ,  = 12
synopsis: "", =
Mitsuha é a filha do prefeito de uma pequena cidade, mas sonha em tentar a sorte em Tóquio. Taki trabalha em um restaurante em Tóquio e deseja largar o seu emprego. Os dois não se conhecem, mas estão conectados pelas imagens de seus sonhos.
trailer: "" = https://youtu.be/3KR8_igDs1Y?si=D2jnf1RybZ0spvET]

title: " ", Akira
genre: "",  = animação 
ageRating: ,  = 14
synopsis: "", = Uma enorme explosão fez com que Tóquio fosse destruída em 1988. Em seu lugar foi construída Neo Tóquio, que, em 2019, sofre com atentados terroristas por toda a cidade. Os amigos Kaneda e Tetsuo integram uma gangue de motoqueiros. Eles disputam rachas violentos com uma gangue rival, os Palhaços, até que um dia Tetsuo encontra Takashi, uma estranha criança com poderes que fugiu do hospital onde era mantido como cobaia.
trailer: "" = Akira (1988) Trailer

title: " ", Festa da salsicha 
genre: "",  = animação 
ageRating: ,  = 16
synopsis: "", = Frank, a salsicha, e seus amigos tentam evitar serem comprados e comidos por humanos em um supermercado
trailer: "" = Festa Da Salsicha | Trailer Dublado | Hoje nos cinemas
{ 
title: "gasparzinho", 
genre: “terror"
ageRating: livre, 
synopsis: "Gasparzinho é um fantasminha camarada que tenta gentilmente assombrar uma mansão no estado do Maine. Ele se apaixona por Kat, uma humana cujo pai tenta se comunicar com espíritos.", 
trailer: "https://youtu.be/iBf6p43uL0s?si=UXVhEBSjXFpzEGtb
" 
},    
{ 
title: "coraline", 
genre: "terror", 
        ageRating: 10, 
synopsis: "Enquanto explora sua nova casa à noite, a pequena Coraline descobre uma porta secreta que contém um mundo parecido com o dela, porém melhor em muitas maneiras. Todos têm botões no lugar dos olhos, os pais são carinhosos e os sonhos de Coraline viram realidade por lá. Ela se encanta com essa descoberta, mas logo percebe que segredos estranhos estão em ação: uma outra mãe e o resto de sua família tentam mantê-la eternamente nesse mundo paralelo.", 
trailer: "https://youtu.be/P8lfdvXkhu0?si=7aSQHUtGxLX_L0wx
" 
}, 
{ 
title: "infestaçã0", 
genre: "terror", 
        ageRating: 12, 
synopsis: "Apaixonado por animais exóticos, Kaleb traz para casa uma aranha venenosa, mas ela acidentalmente foge. Logo, seus vizinhos começam a lutar contra um exército de aranhas mortais e que rapidamente se reproduzem.", 
trailer: "https://youtu.be/LR-uiy20_zM?si=p4adesoKyMJFx_9o
" 
}, 
{ 
title: "medo profundo", 
genre: "terror", 
       ageRating: 14, 
synopsis: "Presas nas profundezas do oceano e cercadas por tubarões-brancos, duas irmãs precisam lutar contra o tempo para permanecer vivas. No entanto, elas têm apenas uma hora de oxigênio e as chances se tornam cada vez menores com os predadores rondando.", 
trailer: "https://youtu.be/KUXMrqPl54Y?si=SDa-sG1p3_97lZj8
" 
}, 
{ 
title: "noite infeliz", 
genre: "terror", 
        ageRating: 16, 
synopsis: "Uma equipe de elite de mercenários invade um complexo familiar na véspera de Natal, deixando todos reféns. No entanto, eles não estão preparados para um combatente surpresa: Papai Noel está no local.", 
trailer: "https://youtu.be/B02N0ao18X4?si=ujYbbEoHKYBEAHl6
" 
}, 
{ 
title: "a casa do lago", 
genre: "suspense", 
        ageRating: livre, 
synopsis: "Uma médica solitária vai morar numa linda casa na beira de um lago, apaixona-se por um arquiteto frustrado, que troca de bilhetes com ela pela caixa de correio da casa onde ela mora. Quando eles descobrem que estão vivendo no mesmo dia, mas com dois anos de diferença, eles resolvem desafiar o tempo e tentam descobrir qual é o mistério atrás do incrível romance deles.", 
trailer: "https://youtu.be/sQGcHQTRijM?si=NllRmlV9kRpJkN5_
" 
}, 
{ 
title: "a casa monstro",
genre: "suspense", 
ageRating: 10, 
synopsis: "Nenhum adulto acredita quando três adolescentes falam que existe uma casa no bairro que é uma criatura perigosa. Com o Dia das Bruxas se aproximando, eles têm que descobrir uma forma de destruir a casa antes que ela faça mal a crianças inocentes.", 
trailer: "https://youtu.be/Iru7Q2qmijQ?si=prhp9sBLAmBP_-i0
" 
}, 
{ 
title: "o misterio da libelula", 
genre: "suspense", 
ageRating: 12, 
synopsis: "A esposa do Dr. Joe Darrow morre fazendo trabalho voluntário na Venezuela. Ele sofre por muito tempo, mas passa a acreditar que ela se comunica com ele. Joe é perseguido por misteriosas libélulas, que o fazem lembrar cada vez mais de sua amada Emily.", 
trailer: "https://youtu.be/-L4vIzAR8nE?si=jtWoi93dwYR9_QBq
" 
}, 
{ 
title: "corra", 
genre: "suspense", 
ageRating: 14, 
synopsis: "Chris é um jovem fotógrafo negro que está prestes a conhecer os pais de Rose, sua namorada caucasiana. Na luxuosa propriedade dos pais dela, Chris percebe que a família esconde algo muito perturbador.", 
trailer: "https://youtu.be/fQ19DupGfzk?si=JrFr7KfyiLKCyOYL
" 
}, 
{ 
title: "os suspeitos", 
genre: "suspense", 
ageRating: 16, 
synopsis: "Depois que sua filha de seis anos e uma amiga dela são sequestradas, Keller Dove, um carpinteiro de Boston, enfrenta o departamento de polícia e o jovem detetive encarregado do caso para fazer justiça com as próprias mãos.", 
trailer: "https://youtu.be/47LneWrxIz8?si=eqDAoexY2lTlgMxF
" 
}, 
{ 
title: "o estranho mundo de jack", 
genre: "ficçao cientifica", 
ageRating: livre, 
synopsis: "Jack Skellington, o Rei das Abóboras, se cansa de fazer o Dia das Bruxas todos os anos e deixa os limites da cidade. Por acaso, acaba atravessando o portal do Natal, onde vê a alegria do espírito natalino. Ao retornar para a Cidade do Halloween, sem ter compreendido o que viu, ele começa a convencer os cidadãos a sequestrarem o Papai Noel e fazerem seu próprio Natal. Apesar de sua leal namorada Sally ser contra, o Papai Noel é capturado e os fatos mostrarão que Sally estava certa o tempo todo.", 
trailer: "https://youtu.be/E8o_8iKS6mk?si=JpIOWS8477prykvr
" 
}, 
{ 
title: "harry potter e o cálice de fogo", 
genre: "ficçao cientifica", 
ageRating: 10, 
synopsis: "Harry retorna para seu quarto ano na Escola de Magia e Bruxaria de Hogwarts, junto com os seus amigos Ron e Hermione. Desta vez, acontece um torneio entre as três maiores escola de magia, com um participante selecionado de cada escola, pelo Cálice de Fogo. O nome de Harry aparece, mesmo não tendo se inscrito, e ele precisa competir.", 
trailer: "https://youtu.be/XO9rqIgzDL0?si=-nO8FsHezDxrATab
" 
}, 
{ 
title: "o jogo da imitação", 
genre: "ficçao cientifica", 
ageRating: 12, 
synopsis: "Em 1939, a recém-criada agência de inteligência britânica MI6 recruta Alan Turing, um aluno da Universidade de Cambridge, para entender códigos nazistas, incluindo o "Enigma", que criptógrafos acreditavam ser inquebrável. A equipe de Turing, incluindo Joan Clarke, analisa as mensagens de "Enigma", enquanto ele constrói uma máquina para decifrá-las. Após desvendar as codificações, Turing se torna herói. Porém, em 1952, autoridades revelam sua homossexualidade, e a vida dele vira um pesadelo.", 
trailer: "https://youtu.be/YmeEz6cQrwM?si=vtqFMpBSxbwg8Zx5
" 
},
{ 
title: "a origem", 
genre: "ficçao cientifica", 
        ageRating: 14, 
synopsis: "Dom Cobb é um ladrão com a rara habilidade de roubar segredos do inconsciente, obtidos durante o estado de sono. Impedido de retornar para sua família, ele recebe a oportunidade de se redimir ao realizar uma tarefa aparentemente impossível: plantar uma ideia na mente do herdeiro de um império. Para realizar o crime perfeito, ele conta com a ajuda do parceiro Arthur, o discreto Eames e a arquiteta de sonhos Ariadne. Juntos, eles correm para que o inimigo não antecipe seus passos.", 
trailer: "https://youtu.be/R_VX0e0PX90?si=BEoOFo30MQEKSF_k
" 
}, 
{ 
title: "laranja mecanica", 
genre: "ficçao cientifica", 
        ageRating: 16, 
synopsis: "O jovem Alex passa as noites com uma gangue de amigos briguentos. Depois que é preso, se submete a uma técnica de modificação de comportamento para poder ganhar sua liberdade.", 
trailer: "https://youtu.be/GdRmiitxQps?si=I17o31mIYvqiKwT_
" 
}, 
{ 
title: "moana", 
genre: "aventura", 
        ageRating: livre, 
synopsis: "Uma jovem parte em uma missão para salvar seu povo. Durante a jornada, Moana conhece o outrora poderoso semideus Maui, que a guia em sua busca para se tornar uma mestre em encontrar caminhos. Juntos, eles navegam pelo oceano em uma viagem incrível.", 
trailer: "https://youtu.be/raLXRLgHHqI?si=E8s8SuoPbMfI4C01
" 
}, 
{ 
title: "interestelar", 
genre: "aventura", 
        ageRating: 10, 
synopsis: "As reservas naturais da Terra estão chegando ao fim e um grupo de astronautas recebe a missão de verificar possíveis planetas para receberem a população mundial, possibilitando a continuação da espécie. Cooper é chamado para liderar o grupo e aceita a missão sabendo que pode nunca mais ver os filhos. Ao lado de Brand, Jenkins e Doyle, ele seguirá em busca de um novo lar.", 
trailer: "https://youtu.be/i6avfCqKcQo?si=D2bu1Y0ZMOkJdBZ_
" 
}, 
{ 
title: "jurassic park", 
genre: "aventura", 
        ageRating: 12, 
synopsis: "Os paleontólogos Alan Grant, Ellie Sattler e o matemático Ian Malcolm fazem parte de um seleto grupo escolhido para visitar uma ilha habitada por dinossauros criados a partir de DNA pré-histórico. O idealizador do projeto e bilionário John Hammond garante a todos que a instalação é completamente segura. Mas após uma queda de energia, os visitantes descobrem, aos poucos, que vários predadores ferozes estão soltos e à caça.", 
trailer: "https://youtu.be/lc0UehYemQA?si=G0wiSTALf0kE81ti
" 
} 

    {
          title: “gladiador”
          genre: “aventura”
          ageRating: 14,
          synopsis: “Maximus é um poderoso general romano, amado pelo povo e pelo imperador Marcus Aurelius. Antes de sua morte, o Imperador desperta a ira de seu filho Commodus ao tornar pública a sua predileção em deixar o trono para Maximus. Sedento pelo poder, Commodus mata seu pai, assume a coroa e ordena a morte de Maximus, que consegue fugir antes de ser pego, e passa a se esconder como um escravo e gladiador enquanto vai atrás de vingança.”
            trailer: “https://youtu.be/P5ieIbInFpg?si=E5L7LlxH7g1X4zxf  “
} 

{ 
           title: “a forma da agua”
           genre: “aventura”
           ageRating: 16,
           synopsis: “Década de 60. Em meio aos grandes conflitos políticos e transformações sociais dos Estados Unidos da Guerra Fria, a muda Elisa, zeladora em um laboratório experimental secreto do governo, se encanta com uma criatura fantástica mantida presa e maltratada no local. Para executar um arriscado e apaixonado resgate, ela recorre ao melhor amigo Giles e à colega de turno Zelda, em uma aventura que pode custar muito mais do que o seu emprego.”
           trailer: “https://youtu.be/XFYWazblaUA?si=g_VdhmwfQ-eExwp7 “
   























];

